version: '3.8'

volumes:
  postgresData:
  rabbitmqData:
  rabbitmqLogData:
services:
  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
    volumes:
      - rabbitmqData:/var/lib/rabbitmq/
      - rabbitmqLogData:/var/log/rabbitmq
      - ${PWD}/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${PWD}/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ${PWD}/docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
    networks:
      - cdc_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3 
  postgres:
    image: postgres:latest
    command:
      - postgres
      - -p 5432
      - "-c"
      - "max_connections=160"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "work_mem=6400kB"
      - "-c"
      - "maintenance_work_mem=100MB"
      - "-c"
      - "effective_cache_size=2500MB"
      - "-c"
      - "random_page_cost=1.0"
      - "-c"
      - "seq_page_cost=1.0"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "shared_preload_libraries=pgoutput"
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
      - ./docker/postgres/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser123
      - POSTGRES_DB=source_db
    networks:
      - cdc_network
  debezium:
    image: quay.io/debezium/server:latest
    ports:
      - 8080:8080
    volumes:
      - ./docker/debezium/conf:/debezium/conf
      - ./docker/debezium/data:/debezium/data
    environment:
      - database.ssl.mode=disable
      - DEBEZIUM_TRUSTED_CERTIFICATES=trustServerCertificate=true
    networks:
      - cdc_network
networks:
  cdc_network:
    driver: bridge
